import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, commonStyles: any, isDarkMode: boolean) => StyleSheet.create({
  safeArea: commonStyles.safeArea,
  container: commonStyles.container,
  scrollContent: { paddingBottom: 40 },
  header: commonStyles.header,
  title: commonStyles.title,
  dotsIcon: { width: 18, height: 18, resizeMode: 'contain', marginTop: 8 },
  dateText: { fontSize: 13, fontFamily: 'AlteHaasGroteskBold', color: theme.textMuted },
  naRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: 5,
    marginTop: 5,
  },
  naText: {
    fontSize: 14,
    fontFamily: 'AlteHaasGroteskBold',
    color: theme.primary,
    marginRight: 8,
  },
  disabledTextAtBottom: {
    fontSize: 13,
    fontFamily: 'AlteHaasGroteskBold',
    color: theme.textMuted,
    textAlign: 'right',
    marginBottom: 15,
  },
  categoryHeader: {
    backgroundColor: theme.surface,
    padding: 8,
    paddingHorizontal: 12,
  },
  categoryHeaderText: {
    fontSize: 11,
    fontFamily: 'AlteHaasGroteskBold',
    color: theme.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  footerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingBottom: 40,
  },
  backBtn: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: theme.buttonBg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: theme.primary,
  },
  buttonGroup: { flex: 1, flexDirection: 'row', marginHorizontal: 10 },
  alertIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  fullImg: { width: '100%', height: '100%', resizeMode: 'contain' },
  cdssBtn: {
    flex: 1,
    height: 50,
    backgroundColor: theme.buttonBg,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: theme.buttonBorder,
    marginRight: 5,
  },
  submitBtn: {
    flex: 1,
    height: 50,
    backgroundColor: theme.buttonBg,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: theme.buttonBorder,
    marginLeft: 5,
  },
  nextBtn: {
    flex: 1,
    marginHorizontal: 10,
    height: 50,
    backgroundColor: theme.buttonBg,
    borderRadius: 25,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: theme.buttonBorder,
  },
  disabledButton: {
    backgroundColor: theme.card,
    borderColor: theme.border,
    opacity: 0.6,
  },
  cdssText: { color: theme.textMuted, fontWeight: 'bold' },
  submitText: { color: theme.primary, fontWeight: 'bold', fontSize: 13 },
  nextText: {
    color: theme.primary,
    fontWeight: 'bold',
    fontSize: 14,
    marginRight: 5,
  },
  fadeBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
  },
  staticPatientContainer: {
    marginBottom: 20,
    backgroundColor: theme.card,
    padding: 15,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border,
  },
  staticPatientLabel: {
    fontFamily: 'AlteHaasGroteskBold',
    color: theme.primary,
    fontSize: 12,
    marginRight: 10,
  },
  staticPatientName: {
    fontFamily: 'AlteHaasGrotesk',
    color: theme.text,
    fontSize: 16,
    fontWeight: 'bold',
  },
});
