import { StyleSheet, Platform } from 'react-native';

export const createStyles = (theme: any, _isDarkMode: boolean) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: theme.background },
    scrollContent: { paddingHorizontal: 40, paddingBottom: 150 },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 25,
      marginTop: Platform.OS === 'ios' ? 20 : 40,
    },
    welcome: {
      fontSize: 35,
      color: theme.primary,
      fontFamily: 'MinionPro-SemiboldItalic',
    },
    date: {
      fontSize: 14,
      color: theme.textMuted,
      marginTop: 4,
      fontFamily: 'AlteHaasGroteskBold',
    },
    searchContainer: { marginBottom: 25 },
    searchBarWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.card,
      borderRadius: 125,
      paddingHorizontal: 15,
      borderWidth: 0,
      height: 50,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    searchIcon: { marginRight: 10 },
    searchBar: {
      flex: 1,
      height: 50,
      color: theme.text,
      fontSize: 15,
      fontFamily: 'AlteHaasGrotesk',
    },
    statsContainer: {
      flexDirection: 'row',
      marginBottom: 30,
      marginTop: 10,
      alignItems: 'center',
    },
    greenVerticalLine: {
      width: 4,
      backgroundColor: theme.secondary,
      height: '120%',
      marginRight: 15,
      borderRadius: 2,
    },
    statsRow: {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    statItem: { alignItems: 'center', flex: 1 },
    circle: {
      width: 60,
      height: 60,
      borderRadius: 60,
      borderWidth: 1,
      borderColor: theme.cardBorder,
      backgroundColor: theme.card2,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
      elevation: 5,
      shadowColor: '#000',
      shadowOpacity: 0.1,
      shadowRadius: 10,
    },
    statIcon: { width: 26, height: 26 },
    statLabel: {
      fontSize: 11,
      color: theme.primary,
      fontFamily: 'AlteHaasGroteskBold',
      textAlign: 'center',
      marginBottom: 2,
    },
    statCount: {
      fontSize: 26,
      color: theme.primary,
      fontFamily: 'AlteHaasGroteskBold',
    },
    filterHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 15,
    },
    sectionTitle: {
      fontSize: 14,
      fontFamily: 'AlteHaasGroteskBold',
      color: theme.textMuted,
    },
    viewAll: {
      color: theme.textMuted,
      fontSize: 14,
      fontFamily: 'AlteHaasGrotesk',
    },
    stickyControls: {
      backgroundColor: theme.background,
      paddingBottom: 18,
    },
    chipsRow: { flexDirection: 'row', marginBottom: -5, paddingBottom: -5 },
    stickyOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      backgroundColor: theme.background,
      paddingHorizontal: 40,
      paddingTop: Platform.OS === 'ios' ? 20 : 40,
      paddingBottom: 10,
      zIndex: 20,
      overflow: 'visible',
    },
    stickyHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 20,
    },
    stickySearchContainer: {
      marginBottom: 16,
    },
    stickyPillsRow: {
      flexDirection: 'row',
      paddingBottom: 20,
    },
    chip: {
      paddingHorizontal: 20,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.filterBg,
      marginRight: 10,
    },
    activeChip: { backgroundColor: theme.filterBg },
    inactiveChip: { backgroundColor: 'transparent' },
    chipText: { fontSize: 12, fontFamily: 'AlteHaasGroteskBold' },
    activeChipText: { color: '#FFF' },
    inactiveChipText: { color: theme.filterBg },
    listContainer: { paddingBottom: 20 },
    patientRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    patientLeft: { flexDirection: 'row', alignItems: 'center' },
    patientLeftExpanded: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    statusDot: { width: 8, height: 8, borderRadius: 4, marginRight: 10 },
    unreadStatusDot: {
      backgroundColor: theme.secondary,
    },
    readStatusDot: {
      backgroundColor: 'transparent',
    },
    avatarContainer: { marginHorizontal: 5 },
    patientName: {
      fontSize: 13,
      color: theme.text,
      fontFamily: 'AlteHaasGrotesk',
    },
    unreadPatientName: {
      fontFamily: 'AlteHaasGroteskBold',
      opacity: 1,
      marginLeft: 12,
    },
    readPatientName: {
      fontFamily: 'AlteHaasGrotesk',
      opacity: 0.95,
      marginLeft: 12,
    },
    patientRightContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      width: 100,
      justifyContent: 'flex-end',
    },
    patientRight: { alignItems: 'flex-end', width: '100%' },
    badge: {
      backgroundColor: theme.updateBadgeBg,
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 12,
      marginBottom: 4,
      width: '100%',
      alignItems: 'center',
    },
    badgeText: {
      color: theme.updateBadgeText,
      fontSize: 11,
      fontFamily: 'AlteHaasGroteskBold',
      textAlign: 'center',
    },
    timeText: {
      color: theme.textMuted,
      fontSize: 11,
      fontFamily: 'AlteHaasGroteskBold',
    },
    stickyFadeWrapper: {
      position: 'absolute',
      left: 0,
      right: 0,
      zIndex: 19,
    },
    stickyFadeBottom: {
      width: '100%',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: 30,
    },
    emptyState: { alignItems: 'center', marginTop: 50 },
    emptyTitle: {
      color: theme.textMuted,
      fontFamily: 'AlteHaasGrotesk',
      fontWeight: 'bold',
      fontSize: 16,
      marginBottom: 5,
    },
    emptySubtitle: {
      color: theme.textMuted,
      fontFamily: 'AlteHaasGrotesk',
      fontSize: 14,
    },
  });
