import { StyleSheet, Platform } from 'react-native';

export const createStyles = (theme: any, isDarkMode: boolean) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: theme.background },
    scrollContent: { paddingHorizontal: 40, paddingBottom: 150 },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 35,
      marginTop: Platform.OS === 'ios' ? 20 : 40,
    },
    welcome: {
      fontSize: 35,
      color: theme.primary,
      fontFamily: 'MinionPro-SemiboldItalic',
    },
    date: {
      fontSize: 14,
      color: theme.textMuted,
      marginTop: 4,
      fontFamily: 'AlteHaasGroteskBold',
    },
    searchContainer: { marginBottom: 25 },
    searchBarWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.card,
      borderRadius: 125,
      paddingHorizontal: 15,
      borderWidth: 0,
      height: 50,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    searchIcon: { marginRight: 10 },
    searchBar: { flex: 1, height: 50, color: theme.text },
    filterSection: { marginBottom: 20 },
    chipsRow: { flexDirection: 'row' },
    chip: {
      paddingHorizontal: 20,
      paddingVertical: 6,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.secondary,
      marginRight: 10,
    },
    activeChip: { backgroundColor: theme.secondary },
    chipText: {
      color: theme.secondary,
      fontSize: 12,
      fontFamily: 'AlteHaasGroteskBold',
    },
    activeChipText: { color: '#FFF' },
    emptyState: { alignItems: 'center', marginTop: 50 },
    emptyTitle: {
      color: theme.textMuted,
      fontFamily: 'AlteHaasGrotesk',
      fontWeight: 'bold',
      fontSize: 16,
      marginBottom: 5,
      textAlign: 'center',
    },
    emptySubtitle: {
      color: theme.textMuted,
      fontFamily: 'AlteHaasGrotesk',
      fontSize: 14,
      textAlign: 'center',
    },
    bottomNav: {
      position: 'absolute',
      bottom: 20,
      left: 20,
      right: 20,
      height: 70,
      backgroundColor: theme.card,
      borderRadius: 35,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 10,
      elevation: 10,
      shadowColor: '#000',
      shadowOpacity: 0.1,
      shadowRadius: 10,
    },
    navItemWrapper: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    navItem: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      width: '100%',
    },
    activeNavItem: { borderRadius: 20 },
    navIconImage: { width: 24, height: 24, marginBottom: 4 },
    navLabel: { fontSize: 10 },
  });
